# A workflow to check for "OOPS" pitfalls of changed ontology files
name: Check if ontology has OOPS! Pitfalls

# Controls when the workflow will run
on: push

jobs:
  print-stuff:
    runs-on: ubuntu-latest
    steps:
      - run: npm install axios
      - run: npm install fs
      - run: npm install rdf-ext
      - uses: actions/checkout@v2
      - uses: actions/github-script@v6
        with:
          script: |
            const { default: printStuff } = await import('rdf-ext');
            await printStuff();