# A workflow to check if rdf-ext works
name: Check if rdf-ext works

# Controls when the workflow will run
on:
  workflow_dispatch

jobs:
  print-stuff:
    runs-on: ubuntu-latest
    steps:
      - run: npm install rdf-ext
      - uses: actions/github-script@v6
        with:
          script: |
            const rdf = await import('node_modules/rdf-ext')
            console.log("Alles Gut!");
