# A workflow to check if rdf-ext works
name: Check if rdf-ext works

# Controls when the workflow will run
on:
  workflow_dispatch

jobs:
  print-stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #- run: npm ci
      - run: npm install rdf-ext
      - uses: actions/github-script@v6
        with:
          script: |
            console.log("Vor import")
            const rdf = require('rdf-ext')
            console.log("Alles Gut!");
